// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBl0yRG-W_9yfX3N4QB0Db8Z6sHHjyHpkc',
    appId: '1:235373409149:web:a88891636ee025b18e5214',
    messagingSenderId: '235373409149',
    projectId: 'puffway-bd952',
    authDomain: 'puffway-bd952.firebaseapp.com',
    storageBucket: 'puffway-bd952.appspot.com',
    measurementId: 'G-SZP0YB3M9B',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCnaflD6umXB2eipGO2In7ZFud80IgOc0Q',
    appId: '1:235373409149:android:85a4d23f49018efa8e5214',
    messagingSenderId: '235373409149',
    projectId: 'puffway-bd952',
    storageBucket: 'puffway-bd952.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBsImEtHoU1br8yGU49zN5cYwIj-jiIOnQ',
    appId: '1:235373409149:ios:97f42f7d6901982d8e5214',
    messagingSenderId: '235373409149',
    projectId: 'puffway-bd952',
    storageBucket: 'puffway-bd952.appspot.com',
    iosClientId: '235373409149-ihcprtamudsd46kt47o0rvci4lh4hcbu.apps.googleusercontent.com',
    iosBundleId: 'com.example.puffway',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBsImEtHoU1br8yGU49zN5cYwIj-jiIOnQ',
    appId: '1:235373409149:ios:97f42f7d6901982d8e5214',
    messagingSenderId: '235373409149',
    projectId: 'puffway-bd952',
    storageBucket: 'puffway-bd952.appspot.com',
    iosClientId: '235373409149-ihcprtamudsd46kt47o0rvci4lh4hcbu.apps.googleusercontent.com',
    iosBundleId: 'com.example.puffway',
  );
}
